pom.xml
src/main/java/com/odysseusinc/arachne/portal/model/AbstractPaperFile.java
src/main/java/com/odysseusinc/arachne/portal/model/PaperPaperFile.java
src/main/java/com/odysseusinc/arachne/portal/model/PaperProtocolFile.java

(cherry picked from commit b068b97)

Fixed adding paper files and protocol files to paper

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseUserRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseUserService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

and return back when user is enabled

ARACHNE-1407 Removes disabled users from expert finder

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseSkillController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/SkillController.java
src/main/java/com/odysseusinc/arachne/portal/repository/SkillRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseSkillService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseSkillServiceImpl.java

Arachne 1475

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java

doAddCommonEntityToAnalysis method

ARACHNE-1521 Moved executable specifying outside

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java

fix redirect for already accepted/decline invitations from email links

ARACHNE-1538

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseUserService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

new upd date after new avatar upload

ARACHNE-1599

---

src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java

study lead search to ignore case

ARACHNE-1461

---

src/test/resources/application.properties

ARACHNE-1611

---

src/main/java/com/odysseusinc/arachne/portal/component/PermissionDslPredicates.java

aArachne 1703

---

src/main/java/com/odysseusinc/arachne/portal/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/BaseAnalysisServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java
src/main/resources/application-base.yml
src/main/resources/application-dev.yml
src/main/resources/application-integration.yml
src/test/java/com/odysseusinc/arachne/portal/config/TestConfig.java
src/test/resources/application.properties

ARACHNE-1796 Changed hostsWhiteList to urlWhiteList and changed related

---

src/test/resources/data/user/not-activated-user.xml

ARACHNE-1843 Security issue. Concurrent Logins Permitted

---

src/main/resources/preprocessor/estimation/run_ple_analysis.R

(cherry picked from commit 685a2aa)

ARACHNE-1950 Updated run_ple_analysis.R

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseUserService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/mail/InvitationApprovalSubmissionArachneMailMessage.java
src/main/java/com/odysseusinc/arachne/portal/service/mail/InvitationArachneMailMessage.java
src/main/java/com/odysseusinc/arachne/portal/service/mail/InvitationDataOwnerMailSender.java
src/main/java/com/odysseusinc/arachne/portal/service/mail/UnlockAnalysisRequestMailMessage.java
src/main/resources/templates/mail/invitation_approval_execute_submission.html
src/main/resources/templates/mail/invitation_approval_publish_submission.html
src/main/resources/templates/mail/invitation_data_owner.html
src/main/resources/templates/mail/unlock_analysis_request.html

(cherry picked from commit 7ace6fb)
ARACHNE-2240

ARACHNE-2156 Fixed user.id demonstration in invitation emails

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/portal/model/StudyType_.java
src/main/java/com/odysseusinc/arachne/portal/model/Submission.java
src/main/java/com/odysseusinc/arachne/portal/model/search/StudySpecification.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseDataSourceRepository.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseUserRepository.java
src/main/java/com/odysseusinc/arachne/portal/repository/DataNodeRepository.java
src/main/java/com/odysseusinc/arachne/portal/repository/submission/BaseSubmissionRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseDataNodeService.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseUserService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseAtlasServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataNodeServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BreadcrumbServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/mail/ArachneMailSender.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java
src/test/resources/application.properties

Arachne 2289

---

src/test/java/com/odysseusinc/arachne/portal/service/BaseDataSourceServiceTest.java

(cherry picked from commit 018c5ae)

fixing of test

---

src/main/java/com/odysseusinc/arachne/portal/repository/AnalysisFileRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/BaseAnalysisServiceImpl.java

fixed appearance of template code files after creating analysis

ARACHNE-2372

---

src/main/resources/db/migration/V20180612210001__fix_workspace_constraints.sql

fixed trigger lead_user_in_workspace logic and improved error messages
in previous migration version the ability to add Contributor to Regular study was broken

ARACHNE-2393 fixed trigger lead_user_in_workspace logic

---

src/main/resources/db/migration/V20180605131308__add_workspace_functionality.sql

fixed old migration issue with constraint

ARACHNE-2393 fix-migration-constraints

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/DataNodeDTO.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/DataNodeToDataNodeDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataNodeServiceImpl.java

added health status check to method

Arachne-2444 Add permissions to datanode and change return type to DataNodeDTO

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeController.java

this return type was changed by mistake

ARACHNE-2444 Changed return type to proper

---

src/main/java/com/odysseusinc/arachne/portal/repository/UserSpecifications.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

changed search pattern - now searched string can match not only the start part of word
search ignores case

ARACHNE-2485. Case insensitive search of users

---

src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataNodeServiceImpl.java

removed extra authorization check for datanode

ARACHNE-2444. Fix DN Authorization check

---

src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseSolrServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/solr/SolrField.java

(cherry picked from commit f765c7e)

ARACHNE-2519. Fixed cast int to string

---

solr_config/conf/managed-schema
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/CommonDataNodeRegisterDTOToDataNodeConverter.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/SearchDTOToSolrQuery.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseRawDataSourceRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseDataNodeService.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseDataSourceService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataNodeServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseGlobalSearchServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/DataNodeServiceImpl.java

changed type of "query" field for solr
added functionality to enable search special symbols with solr
added reindex after dataNode's name was updated

ARACHNE-2474. Fixed data catalog search

---

src/main/java/com/odysseusinc/arachne/portal/service/impl/OrganizationServiceImpl.java

Fixes Manual datanode cannot be created

Fixes Manual datanode cannot be created

---

src/main/resources/templates/mail/invitation_approval_execute_submission.html
src/main/resources/templates/mail/invitation_approval_publish_submission.html
src/main/resources/templates/mail/invitation_collaborator.html
src/main/resources/templates/mail/invitation_data_owner.html
src/main/resources/templates/mail/new_data_source.html
src/main/resources/templates/mail/new_user.html
src/main/resources/templates/mail/registration.html
src/main/resources/templates/mail/remind_password.html
src/main/resources/templates/mail/unlock_analysis_request.html

(cherry picked from commit 89fb264)

ARACHNE-2552 - Correct text in email to admin (#554)

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/portal/model/BaseDataSource.java
src/main/java/com/odysseusinc/arachne/portal/model/security/Tenant.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseDataSourceRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseDataSourceService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java
src/main/resources/db/migration/V20181130150600__deleted-column-for-tenants-data-sources.sql

(cherry picked from commit 6f7ea00)

ARACHNE-2494 - Soft deleting for ds' tenants

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/datasource/DataSourceToCommonDataSourceHealthStatusDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseRawDataSourceRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseDataSourceService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java

(cherry picked from commit 211c7e9)

ARACHNE-2550 Datanode: DS health check fails (prod env)

---

src/main/java/com/odysseusinc/arachne/portal/service/mail/InvitationApprovalSubmissionArachneMailMessage.java

issue-586: fix missing '/' in the studyURL

---

src/main/java/com/odysseusinc/arachne/portal/config/properties/AntivirusProperties.java
src/main/java/com/odysseusinc/arachne/portal/config/properties/DefaultExecutorConfigValues.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/AnalysisPreprocessorService.java
src/main/resources/application-base.yml

Clean up default configuration
Increase antivirus jobs queue length from 10 to 50

Issue-600: Extract common default thread pool config, antivirus jobs queue length to 50

---

pom.xml
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/portal/model/BaseDataSource.java
src/main/java/com/odysseusinc/arachne/portal/model/DataSource.java
src/main/java/com/odysseusinc/arachne/portal/model/IDataSource.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/ImportServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/util/BaseStudyHelper.java

resolves OHDSI/ArachneCommons#181

conforms arachne commons restructurization

---

pom.xml
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAchillesController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAdminController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeCommonAnalysisController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataNodeMessagingController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/RoleController.java
src/main/java/com/odysseusinc/arachne/portal/config/AntivirusConfig.java
src/main/java/com/odysseusinc/arachne/portal/config/SwaggerConfig.java

- update swagger and some related dependencies in order to migrate away from swagger bugs and improve performance

Improve swagger documentation

---

README.md

Arachne Community Edition build and run manual
Closes #415

Arachne build and run manual

---

src/main/resources/application-dev.yml

Configure proper logging in DEV profile

configure proper logging for the development profile

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/portal/repository/BaseDataSourceRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

Fixes OHDSI/ArachneNodeAPI#333

Fixes Failing of DataSource update in Network mode

---

src/main/java/com/odysseusinc/arachne/portal/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/portal/security/AuthenticationTokenFilter.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/test/java/com/odysseusinc/arachne/portal/TestApplication.java

Fixes Build number is not loaded in some cases

---

.gitignore
pom.xml
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAdminController.java

Fixes #623 
- change controller arguments from id to username

issue-623 Error assigning admin role to user

---

src/main/java/com/odysseusinc/arachne/portal/model/ArachneFile.java

add filename sanitation

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAuthenticationController.java
src/main/java/com/odysseusinc/arachne/portal/service/LoginAttemptService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/LoginAttemptServiceImpl.java

message changes from "...try again later" to e.g. "... try again in 3 minutes".
Closes #627

Show account lock period for the exceeded number of unsuccessful login attempts 

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java

Do not allow to run 2 concurrent imports into the same analysis

Do not allow to run 2 concurrent imports into the same analysis

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/CreateStudyDTO.java

Make validation message context specific - "Study type should be defined"

Study type mandatory - validation message

---

src/main/java/com/odysseusinc/arachne/portal/repository/BaseStudyRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java

user's workspace should not be visible for inviting experts

user's workspace should not be visible for inviting experts

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java

Hides Pathways analysis type until it completely implemented

Hides Pathway analysis type

---

src/main/resources/db/migration/V20191025141243__users_studies_extended.sql

Fix bug which prevents the owner of the multiple datasources to be displayed more than one time as study participant in the participant's view

grouping participant roles bug

---

pom.xml

set 0.0.2-QA version of Authenticator

set 0.0.2-QA version of Authenticator

---

pom.xml

set commons-io version for CentralAPI pom and it's dependencies

set commons-io version 

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAuthenticationController.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/LoginAttemptServiceImpl.java

fixes: ARACHNE-2767 500 error code during authorization with empty credentials
- add backend validation
- NPE check income argument in LoginAttemptServiceImpl.java

ARACHNE-2767 -500 error code during authorization with empty credentials

---

pom.xml
src/main/java/com/odysseusinc/arachne/portal/service/ToPdfConverter.java
src/main/resources/application-base.yml
src/test/resources/application.properties

recreate JodConverter temp working folder which can be deleted by e.g. system

JodConverter working folder recovery

---

src/main/resources/application-base.yml

Fix jod converter temp folder recovery

Fix jod converter temp folder recovery

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/AnalysisController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/AnalysisFilesSavingService.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/BaseAnalysisService.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisFilesSavingServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisUtils.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/BaseAnalysisServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/util/AnalysisHelper.java

generate analysis description field during import

generate analysis description field during import

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/AnalysisFileToAnalysisFileDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisFilesSavingServiceImpl.java
src/test/java/com/odysseusinc/arachne/portal/service/analysis/AnalysisFilesSavingServiceImplTest.java

Import analysis

---

src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisFilesSavingServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/ExecutableDetector.java

extract analysis detector to separate component

extract analysis detector 

---

pom.xml

update version set authenticator 0.0.3-QA version

update version set authenticator 0.0.3-QA version

---

src/main/java/com/odysseusinc/arachne/portal/config/FlywayConfig.java

ARACHNE-2801 migration for java scripts are failed

Change flyway migration order. Migration runs after spring context already initialized 

---

src/main/resources/db/migration/V20200311165500__set-correct-country-for-states.sql

FIxes #2806
set proper country for some states

ARACHNE-2806 set proper country for some states

---

src/main/resources/db/migration/V20200311165500__set-correct-country-for-states.sql
src/main/resources/db/migration/V20200313111500__trim-states-provinces-names.sql

ARACHNE-2806 
fix states that mistakenly ended up under the wrong countries

ARACHNE-2806 fix states that mistakenly ended up under the wrong countries

---

pom.xml

upgrade sqlRender version

---

src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java

refresh invitation to execute a submission on new submission

refresh invitation to execute a submission on new submission

---

src/main/resources/application-base.yml

upload submission: exceeds the configured maximum [ARACHNE-2818]

---

src/main/resources/application-base.yml

Upload limits

---

src/main/resources/r/run_ir_analysis.r

- pass result schema as temp schema to the SqlRender
- replace usage of deprecated translateSql method with translate

IR fails on BigQuery

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/BaseAnalysisServiceImpl.java

update real file name on rename

update real file name on rename

---

README.md
pom.xml

update version to 1.16.2-snapshot

update version to 1.16.2-snapshot

---

src/main/java/com/odysseusinc/arachne/portal/security/AuthenticationTokenFilter.java

Fixes https://odysseusdataservices.atlassian.net/browse/ARACHNE-2772
Log authentication exception only for debug mode

ARACHNE-2772 token invalid Error message floods into log

---

src/main/java/com/odysseusinc/arachne/portal/security/AuthenticationTokenFilter.java

rollback incorrect change

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/submission/BaseSubmissionController.java
src/main/java/com/odysseusinc/arachne/portal/util/SubmissionHelper.java

IR cohorts names fix

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/datasource/BaseDataSourceDTOToDataSourceConverter.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/datasource/BaseDataSourceToCommonDataSourceDTOConverter.java

hide obsolete datasource uid

---

src/main/java/com/odysseusinc/arachne/portal/model/Analysis.java
src/main/java/com/odysseusinc/arachne/portal/service/analysis/impl/AnalysisFilesSavingServiceImpl.java
src/main/resources/db/migration/V20200909150000__analyses_description.sql

Control analysis description length on import

extend analysis description field and truncate by the limit on import

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAdminController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/ArachneConsts.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/BreadcrumbDTO.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/BreadcrumbToBreadcrumbDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/GlobalSearchResultToGlobalSearchResultDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/model/solr/SolrCollection.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseGlobalSearchServiceImpl.java

UserId should be encoded as a hash in the general search

Hashed userId in the general search results

---

src/main/java/com/odysseusinc/arachne/portal/repository/BaseUserRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

allows remove any kind of user from admins

remove any users from admins

---

src/main/java/com/odysseusinc/arachne/portal/model/Analysis.java
src/main/java/com/odysseusinc/arachne/portal/model/AnalysisFile.java
src/main/java/com/odysseusinc/arachne/portal/model/listeners/AnalysisChangesListener.java

refresh study Update date on change in analysis and analysis code

refresh study Update date on change in analysis and analysis code

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/submission/BaseSubmissionController.java
src/main/java/com/odysseusinc/arachne/portal/repository/StudyDataSourceLinkRepository.java
src/main/java/com/odysseusinc/arachne/portal/repository/UserStudyRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/BaseUserService.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java

cleanup invitation notifications

Study notifications cleanup

---

pom.xml

remove redundant dependency

---

src/main/java/com/odysseusinc/arachne/portal/repository/BaseStudyRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java

index studies for all tenants

---

src/main/java/com/odysseusinc/arachne/portal/model/listeners/AnalysisChangesListener.java

analysis Changes listener changes

---

pom.xml
src/main/java/com/odysseusinc/arachne/portal/repository/CommentRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/AchillesImportServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/CommentServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java

jackson-databind version update

jackson-databind version update

---

pom.xml

update to the patch version jackson-databind:2.7.5.1

update to the patch version jackson-databind:2.7.5.1

---

pom.xml

activemq dependency update

---

pom.xml
solr_config/conf/solrconfig.xml
src/main/docker/Dockerfile

switch to the new base docker image

switch to the new base docker image

---

pom.xml

add support for the latest java 8 version

ARACHNE-2901 support the latest java 8 version

---

src/main/java/com/odysseusinc/arachne/portal/repository/BaseRawUserRepository.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseUserServiceImpl.java
src/main/resources/application-base.yml
src/test/resources/application.properties

Case Insensitive Login

---

src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseStudyServiceImpl.java

Fixed sorting by "Updated" column in Study 

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/DataSourceDTO.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/datasource/BaseDataSourceDTOToDataSourceConverter.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/dto/converters/datasource/BaseDataSourceToCommonDataSourceDTOConverter.java
src/main/java/com/odysseusinc/arachne/portal/model/BaseDataSource.java
src/main/java/com/odysseusinc/arachne/portal/model/DataSource.java
src/main/java/com/odysseusinc/arachne/portal/model/IDataSource.java
src/main/java/com/odysseusinc/arachne/portal/service/impl/BaseDataSourceServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/study/impl/AddDataSourceStrategyFactoryImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/study/impl/AddRestrictedDataSourceStrategy.java
src/main/resources/db/migration/V20210622115059__datasource_access_type.sql

fixes https://github.com/OHDSI/ArachneUI/issues/825

Fixed adding access type to Data Sources

---

src/main/java/com/odysseusinc/arachne/portal/service/study/impl/AddDataSourceStrategyFactoryImpl.java

Fixed adding strategy for virtual datasource

---

src/main/resources/db/migration/V20210622115059__datasource_access_type.sql

fixes https://github.com/OHDSI/ArachneUI/issues/825

Data source view is now created

---

src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/SubmissionServiceImpl.java
src/main/resources/application-base.yml

Changed visibility of submission results for user without approved invite

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/submission/BaseSubmissionController.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/BaseSubmissionService.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java

Submission info is updated before approving

---

src/main/java/com/odysseusinc/arachne/portal/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/portal/config/tenancy/TenantContext.java
src/main/java/com/odysseusinc/arachne/portal/model/security/ArachneUser.java
src/main/java/com/odysseusinc/arachne/portal/model/security/HasTenant.java
src/main/java/com/odysseusinc/arachne/portal/security/AuthenticationSystemTokenFilter.java
src/main/java/com/odysseusinc/arachne/portal/security/DataNodeAuthenticationToken.java
src/main/java/com/odysseusinc/arachne/portal/util/BaseStudyHelper.java

Tenant id was missing after thread local contamination issue that was providing it was removed in d5ed8ea16

In DataNodeAuthenticationToken, add tenant id

---

src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAnalysisController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAuthenticationController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseExpertFinderController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseSkillController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseUserController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/GlobalSearchController.java
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/submission/BaseSubmissionController.java
src/main/java/com/odysseusinc/arachne/portal/security/AuthenticationTokenFilter.java
src/main/java/com/odysseusinc/arachne/portal/service/submission/impl/BaseSubmissionServiceImpl.java
src/main/java/com/odysseusinc/arachne/portal/util/UserUtils.java

Username is not present in oidc token and no service or controller code should rely on that.

Update controllers that rely on username from token to deal with spring Authentication instead

---

src/main/java/com/odysseusinc/arachne/portal/service/ExternalLoginService.java

As the former is not properly instantiated in tests (due to some obscure spring-data configuration problem that can take ages to troubleshoot)

In ExternalLoginService, remove using RawUserRepository in favor of EntityManager

---

pom.xml
solr_config/conf/solrconfig.xml
src/main/java/com/odysseusinc/arachne/portal/api/v1/controller/BaseAdminController.java

- Changes cache implementation to required by Solr 8 CaffeineCache
- Fixes re-index procedure in multi-tenant environment

ARACHNE-3089 Search on Navigation Bar does not work
